import { createHash } from "node:crypto";

/**
 * Stage-scoped signing material for the Gateway identity and mnemo transport
 * trust boundaries. Values are generated by Pulumi and never committed. The
 * identity key is stored in Secrets Manager; ECS reads the transport key from a
 * stage-scoped SSM SecureString parameter.
 */
export interface NamespaceIdentityOutputs {
  identitySigningKeys: Output<string>;
  transportSigningKeys: Output<string>;
  transportSigningParameterArn: Output<string>;
  transportSigningRevision: Output<string>;
}

export interface MaintenanceIdentityOutputs {
  bundle: Output<string>;
  bundleParameterArn: Output<string>;
  revision: Output<string>;
  serviceParameterArns: Record<string, Output<string>>;
}

export function maintenanceServiceIdentity(): MaintenanceIdentityOutputs {
  const rotation = transportSigningKeyConfig({
    MEM9_TRANSPORT_SIGNING_ACTIVE_SLOT: process.env.MEM9_SERVICE_SIGNING_ACTIVE_SLOT,
    MEM9_TRANSPORT_SIGNING_SLOT_A_REVISION: process.env.MEM9_SERVICE_SIGNING_SLOT_A_REVISION,
    MEM9_TRANSPORT_SIGNING_SLOT_B_REVISION: process.env.MEM9_SERVICE_SIGNING_SLOT_B_REVISION,
  });
  const tags = { Project: "mem9-on-aws", Stage: $app.stage, ManagedBy: "sst" };
  const rings: Record<string, Output<string>> = {};
  const serviceParameterArns: Record<string, Output<string>> = {};
  for (const service of ["consolidation", "cleanup", "analysis"]) {
    const title = service[0].toUpperCase() + service.slice(1);
    const a = new random.RandomPassword(`Mem9Service${title}SigningKeyA`, {
      length: 64, special: false, keepers: { revision: rotation.slotARevision },
    });
    const b = new random.RandomPassword(`Mem9Service${title}SigningKeyB`, {
      length: 64, special: false, keepers: { revision: rotation.slotBRevision },
    });
    rings[service] = a.result.apply((left: string) => b.result.apply((right: string) =>
      JSON.stringify({ active: rotation.activeSlot, a: left, b: right })));
    const parameter = new aws.ssm.Parameter(`Mem9Service${title}SigningKeys`, {
      name: `/mem9-on-aws/${$app.stage}/namespace/service-${service}-signing-keys`,
      type: "SecureString", value: rings[service], tags,
    });
    serviceParameterArns[service] = parameter.arn;
  }
  const bundle = rings.consolidation.apply(consolidation => rings.cleanup.apply(cleanup =>
    rings.analysis.apply(analysis => JSON.stringify({
      consolidation: JSON.parse(consolidation), cleanup: JSON.parse(cleanup), analysis: JSON.parse(analysis),
    }))));
  const parameter = new aws.ssm.Parameter("Mem9ServiceTransportSigningKeys", {
    name: `/mem9-on-aws/${$app.stage}/namespace/service-transport-signing-keys`,
    type: "SecureString", value: bundle, tags,
  });
  return { bundle, bundleParameterArn: parameter.arn,
    revision: bundle.apply(value => createHash("sha256").update(value).digest("hex")),
    serviceParameterArns };
}

export interface TransportSigningKeyConfig {
  activeSlot: "a" | "b";
  slotARevision: string;
  slotBRevision: string;
}

const TRANSPORT_KEY_REVISION_PATTERN =
  /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/;

export function transportSigningKeyConfig(
  env: NodeJS.ProcessEnv = process.env,
): TransportSigningKeyConfig {
  const activeSlot = env.MEM9_TRANSPORT_SIGNING_ACTIVE_SLOT || "a";
  if (activeSlot !== "a" && activeSlot !== "b") {
    throw new Error("MEM9_TRANSPORT_SIGNING_ACTIVE_SLOT must be a or b");
  }

  const slotARevision =
    env.MEM9_TRANSPORT_SIGNING_SLOT_A_REVISION || "v1";
  const slotBRevision =
    env.MEM9_TRANSPORT_SIGNING_SLOT_B_REVISION || "v1";
  for (const [name, value] of [
    ["MEM9_TRANSPORT_SIGNING_SLOT_A_REVISION", slotARevision],
    ["MEM9_TRANSPORT_SIGNING_SLOT_B_REVISION", slotBRevision],
  ] as const) {
    if (!TRANSPORT_KEY_REVISION_PATTERN.test(value)) {
      throw new Error(
        `${name} must be 1-64 alphanumeric, dot, underscore, or hyphen characters`,
      );
    }
  }

  return { activeSlot, slotARevision, slotBRevision };
}

function signingSecret(
  logicalName: string,
  nameSuffix: string,
  description: string,
): { value: Output<string>; arn: Output<string> } {
  const tags = { Project: "mem9-on-aws", Stage: $app.stage, ManagedBy: "sst" };
  const secret = new aws.secretsmanager.Secret(logicalName, {
    namePrefix: `mem9-on-aws-${$app.stage}-${nameSuffix}-`,
    description,
    recoveryWindowInDays: $app.stage === "prod" ? 7 : 0,
    tags,
  });
  const password = new random.RandomPassword(`${logicalName}Value`, {
    length: 64,
    special: false,
  });
  const value = password.result.apply((current: string) =>
    JSON.stringify({ current }),
  );
  const version = new aws.secretsmanager.SecretVersion(
    `${logicalName}Version`,
    {
      secretId: secret.id,
      secretString: value,
    },
  );
  return {
    value,
    arn: version.arn.apply(() => secret.arn),
  };
}

export function namespaceIdentity(): NamespaceIdentityOutputs {
  const transportConfig = transportSigningKeyConfig();
  const identity = signingSecret(
    "Mem9IdentitySigningKeys",
    "identity-signing-keys",
    "Gateway interceptor to target request-context signing keys.",
  );
  const transportSlotA = new random.RandomPassword(
    "Mem9TransportSigningKeySlotA",
    {
      length: 64,
      special: false,
      keepers: { revision: transportConfig.slotARevision },
    },
  );
  const transportSlotB = new random.RandomPassword(
    "Mem9TransportSigningKeySlotB",
    {
      length: 64,
      special: false,
      keepers: { revision: transportConfig.slotBRevision },
    },
  );
  const transportSigningKeys = transportSlotA.result.apply(
    (slotA: string) =>
      transportSlotB.result.apply((slotB: string) =>
        JSON.stringify({
          active: transportConfig.activeSlot,
          a: slotA,
          b: slotB,
        }),
      ),
  );
  const transportSigningRevision = transportSigningKeys.apply(
    (value: string) =>
      createHash("sha256").update(value).digest("hex"),
  );
  const transportParameter = new aws.ssm.Parameter(
    "Mem9TransportSigningKeys",
    {
      name: `/mem9-on-aws/${$app.stage}/namespace/transport-signing-keys`,
      type: "SecureString",
      value: transportSigningKeys,
      tags: {
        Project: "mem9-on-aws",
        Stage: $app.stage,
        ManagedBy: "sst",
      },
    },
  );
  return {
    identitySigningKeys: identity.value,
    transportSigningKeys,
    transportSigningParameterArn: transportParameter.arn,
    transportSigningRevision,
  };
}
