/**
 * Stage-scoped signing material for the Gateway identity and mnemo transport
 * trust boundaries. Values are generated by Pulumi, stored in Secrets Manager,
 * and never committed. The ECS task consumes only the transport secret ARN.
 */
export interface NamespaceIdentityOutputs {
  identitySigningKeys: Output<string>;
  transportSigningKeys: Output<string>;
  transportSigningSecretArn: Output<string>;
}

function signingSecret(
  logicalName: string,
  nameSuffix: string,
  description: string,
): { value: Output<string>; arn: Output<string> } {
  const tags = { Project: "mem9-on-aws", Stage: $app.stage, ManagedBy: "sst" };
  const secret = new aws.secretsmanager.Secret(logicalName, {
    namePrefix: `mem9-on-aws-${$app.stage}-${nameSuffix}-`,
    description,
    recoveryWindowInDays: $app.stage === "prod" ? 7 : 0,
    tags,
  });
  const password = new random.RandomPassword(`${logicalName}Value`, {
    length: 64,
    special: false,
  });
  const value = password.result.apply((current: string) =>
    JSON.stringify({ current }),
  );
  const version = new aws.secretsmanager.SecretVersion(
    `${logicalName}Version`,
    {
      secretId: secret.id,
      secretString: value,
    },
  );
  return {
    value,
    arn: version.arn.apply(() => secret.arn),
  };
}

export function namespaceIdentity(): NamespaceIdentityOutputs {
  const identity = signingSecret(
    "Mem9IdentitySigningKeys",
    "identity-signing-keys",
    "Gateway interceptor to target request-context signing keys.",
  );
  const transport = signingSecret(
    "Mem9TransportSigningKeys",
    "transport-signing-keys",
    "Gateway target to mnemo-server transport signing keys.",
  );
  return {
    identitySigningKeys: identity.value,
    transportSigningKeys: transport.value,
    transportSigningSecretArn: transport.arn,
  };
}
