import { createHash } from "node:crypto";

/**
 * Stage-scoped signing material for the Gateway identity and mnemo transport
 * trust boundaries. Values are generated by Pulumi and never committed. The
 * identity key is stored in Secrets Manager; ECS reads the transport key from a
 * stage-scoped SSM SecureString parameter.
 */
export interface NamespaceIdentityOutputs {
  identitySigningKeys: Output<string>;
  transportSigningKeys: Output<string>;
  transportSigningParameterArn: Output<string>;
  transportSigningRevision: Output<string>;
}

export interface TransportSigningKeyConfig {
  activeSlot: "a" | "b";
  slotARevision: string;
  slotBRevision: string;
}

const TRANSPORT_KEY_REVISION_PATTERN =
  /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/;

export function transportSigningKeyConfig(
  env: NodeJS.ProcessEnv = process.env,
): TransportSigningKeyConfig {
  const activeSlot = env.MEM9_TRANSPORT_SIGNING_ACTIVE_SLOT || "a";
  if (activeSlot !== "a" && activeSlot !== "b") {
    throw new Error("MEM9_TRANSPORT_SIGNING_ACTIVE_SLOT must be a or b");
  }

  const slotARevision =
    env.MEM9_TRANSPORT_SIGNING_SLOT_A_REVISION || "v1";
  const slotBRevision =
    env.MEM9_TRANSPORT_SIGNING_SLOT_B_REVISION || "v1";
  for (const [name, value] of [
    ["MEM9_TRANSPORT_SIGNING_SLOT_A_REVISION", slotARevision],
    ["MEM9_TRANSPORT_SIGNING_SLOT_B_REVISION", slotBRevision],
  ] as const) {
    if (!TRANSPORT_KEY_REVISION_PATTERN.test(value)) {
      throw new Error(
        `${name} must be 1-64 alphanumeric, dot, underscore, or hyphen characters`,
      );
    }
  }

  return { activeSlot, slotARevision, slotBRevision };
}

function signingSecret(
  logicalName: string,
  nameSuffix: string,
  description: string,
): { value: Output<string>; arn: Output<string> } {
  const tags = { Project: "mem9-on-aws", Stage: $app.stage, ManagedBy: "sst" };
  const secret = new aws.secretsmanager.Secret(logicalName, {
    namePrefix: `mem9-on-aws-${$app.stage}-${nameSuffix}-`,
    description,
    recoveryWindowInDays: $app.stage === "prod" ? 7 : 0,
    tags,
  });
  const password = new random.RandomPassword(`${logicalName}Value`, {
    length: 64,
    special: false,
  });
  const value = password.result.apply((current: string) =>
    JSON.stringify({ current }),
  );
  const version = new aws.secretsmanager.SecretVersion(
    `${logicalName}Version`,
    {
      secretId: secret.id,
      secretString: value,
    },
  );
  return {
    value,
    arn: version.arn.apply(() => secret.arn),
  };
}

export function namespaceIdentity(): NamespaceIdentityOutputs {
  const transportConfig = transportSigningKeyConfig();
  const identity = signingSecret(
    "Mem9IdentitySigningKeys",
    "identity-signing-keys",
    "Gateway interceptor to target request-context signing keys.",
  );
  const transportSlotA = new random.RandomPassword(
    "Mem9TransportSigningKeySlotA",
    {
      length: 64,
      special: false,
      keepers: { revision: transportConfig.slotARevision },
    },
  );
  const transportSlotB = new random.RandomPassword(
    "Mem9TransportSigningKeySlotB",
    {
      length: 64,
      special: false,
      keepers: { revision: transportConfig.slotBRevision },
    },
  );
  const transportSigningKeys = transportSlotA.result.apply(
    (slotA: string) =>
      transportSlotB.result.apply((slotB: string) =>
        JSON.stringify({
          active: transportConfig.activeSlot,
          a: slotA,
          b: slotB,
        }),
      ),
  );
  const transportSigningRevision = transportSigningKeys.apply(
    (value: string) =>
      createHash("sha256").update(value).digest("hex"),
  );
  const transportParameter = new aws.ssm.Parameter(
    "Mem9TransportSigningKeys",
    {
      name: `/mem9-on-aws/${$app.stage}/namespace/transport-signing-keys`,
      type: "SecureString",
      value: transportSigningKeys,
      tags: {
        Project: "mem9-on-aws",
        Stage: $app.stage,
        ManagedBy: "sst",
      },
    },
  );
  return {
    identitySigningKeys: identity.value,
    transportSigningKeys,
    transportSigningParameterArn: transportParameter.arn,
    transportSigningRevision,
  };
}
