import {createHash} from 'node:crypto';
import {crc32} from 'node:zlib';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {join} from 'node:path';
import {NONROOT_POSTAPPLY_FUNCTIONS as names,NONROOT_POSTAPPLY_RESOURCES as resources,NONROOT_POSTAPPLY_SOURCE_PATHS as paths,NONROOT_POSTAPPLY_ENVIRONMENT as envKeys,NONROOT_POSTAPPLY_POLICY_HASH} from './lib/nonroot-postapply.mjs';
import {nonrootHash as hash} from './lib/production-nonroot-contracts.mjs';
export const sha=b=>createHash('sha256').update(b).digest('hex');
export const repo=fileURLToPath(new URL('../',import.meta.url));
const policy=Statement=>({Version:'2012-10-17',Statement}),allow=(Action,Resource)=>({Effect:'Allow',Action,Resource});
export function zipFile(text){const content=Buffer.from(text),name=Buffer.from('index.mjs'),local=Buffer.alloc(30),central=Buffer.alloc(46),end=Buffer.alloc(22);local.writeUInt32LE(0x04034b50);local.writeUInt16LE(20,4);local.writeUInt32LE(crc32(content),14);local.writeUInt32LE(content.length,18);local.writeUInt32LE(content.length,22);local.writeUInt16LE(name.length,26);central.writeUInt32LE(0x02014b50);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt32LE(crc32(content),16);central.writeUInt32LE(content.length,20);central.writeUInt32LE(content.length,24);central.writeUInt16LE(name.length,28);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(1,8);end.writeUInt16LE(1,10);end.writeUInt32LE(central.length+name.length,12);end.writeUInt32LE(local.length+name.length+content.length,16);return Buffer.concat([local,name,content,central,name,end]);}
export async function postApplyFixture({account='0'.repeat(12),region='us-east-1',tree='b'.repeat(40),source}={}){
 const ar=(service,tail)=>`arn:aws:${service}:${service==='iam'?'':region}:${account}:${tail}`,key=ar('kms','key/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee'),boundary=ar('iam','policy/mem9-on-aws-workload-boundary');
 const r=Object.fromEntries(Object.entries(resources).map(([k,s])=>[k,Object.fromEntries(s.fields.map(f=>[f,null]))]));
 for(const [name,path]of Object.entries({Mem9TransportSigningKeys:'/namespace/transport-signing-keys',SsmOauthStateHmacKey:'/oauth/state-hmac-key',Mem9AlertWebhookParameter:'/observability/slack-webhook-url'})){const n='/mem9-on-aws/prod'+path;Object.assign(r[name],{name:n,arn:ar('ssm','parameter'+n),type:'SecureString',keyId:key,version:2});}
 // IaC namePrefix adds a generated name suffix; Secrets Manager then adds
 // its separate six-character suffix to the full name in the ARN.
 for(const [name,n]of Object.entries({Mem9TenantApiKey:'tenant-api-key',Mem9IdentitySigningKeys:'identity-signing-keys'})){const generatedName='mem9-on-aws-prod-'+n+'-synthetic7f3c9a';Object.assign(r[name],{name:generatedName,arn:ar('secretsmanager','secret:'+generatedName+'-ABCDEF'),kmsKeyId:key});}
 r.AlertExecutionFailureQueue.arn=ar('sqs','mem9-on-aws-prod-AlertExecutionFailureQueue-abcdef');
 const functions={},zips={};for(const name of names){const zip=zips[name]=zipFile(`export const handler=()=>${JSON.stringify(name)};`),digest=sha(zip),roleName='mem9-on-aws-prod-'+name+'Role-abcdefhk';functions[name]={arn:ar('lambda','function:mem9-on-aws-prod-'+name+'Function-abcdefhk'),codeSha256:Buffer.from(digest,'hex').toString('base64'),s3Key:`assets/${name}-code-${digest}.zip`,runtime:'nodejs24.x',architectures:['arm64'],handler:'server-index.handler',role:{arn:ar('iam','role/'+roleName),name:roleName,uniqueId:'AROASYNTHETIC'+name.toUpperCase(),assumeRolePolicy:policy([{Effect:'Allow',Action:'sts:AssumeRole',Principal:{Service:'lambda.amazonaws.com'}}]),inlinePolicies:[{name:'inline',policy:null}],managedPolicyArns:['arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole',...(name==='Mem9ProxyFn'?['arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole']:[])],permissionsBoundary:['Mem9ProxyFn','Mem9IdentityInterceptorFn'].includes(name)?ar('iam','policy/mem9-on-aws-gateway-boundary'):boundary},environment:Object.fromEntries(envKeys[name].map(k=>[k,'synthetic'])),vpcConfig:null,zip:{sha256:digest,bytes:zip.length}};Object.assign(functions[name].environment,{STAGE:'prod',MEM9_SECRET_ACCOUNT_ID:account});}
 const fn=functions,proxy=fn.Mem9ProxyFn;
 Object.assign(proxy.environment,{MEM9_SERVER_BASE_URL:'http://mnemo-server.local:8080/',MEM9_API_KEY_SECRET_ARN:r.Mem9TenantApiKey.arn,MEM9_IDENTITY_SIGNING_KEYS_SECRET_ARN:r.Mem9IdentitySigningKeys.arn,MEM9_TRANSPORT_SIGNING_KEYS_PARAMETER_ARN:r.Mem9TransportSigningKeys.arn,MEM9_TRANSPORT_ISSUER:'gateway-target',MEM9_SECRET_ENDPOINT_MODE:'private',MEM9_ACCEPTANCE_STAGE:''});
 Object.assign(fn.Mem9IdentityInterceptorFn.environment,{MEM9_IDENTITY_SIGNING_KEYS_SECRET_ARN:r.Mem9IdentitySigningKeys.arn,MEM9_ACCEPTANCE_STAGE:''});
 Object.assign(fn.Mem9OauthFacadeFn.environment,{SSM_PREFIX:'/mem9-on-aws/prod',AUTH_MODE:'managed',AUTH_CREDENTIAL_PREFIX:'/mem9-on-aws/prod/cognito/reader',AUTH_TOKEN_AUTH_METHOD:'client_secret_post',COGNITO_TOKEN_ENDPOINT:'https://auth.example.com/oauth2/token',RESOURCE_SCOPES:'mem9-mcp/read,mem9-mcp/write',OAUTH_STATE_HMAC_KEY_PARAMETER_ARN:r.SsmOauthStateHmacKey.arn});
 fn.Mem9AlertRouter.environment.SLACK_WEBHOOK_URL_PARAMETER_ARN=r.Mem9AlertWebhookParameter.arn;
 for(const name of names){const secrets=name==='Mem9ProxyFn'?[r.Mem9TenantApiKey.arn,r.Mem9IdentitySigningKeys.arn]:name==='Mem9IdentityInterceptorFn'?[r.Mem9IdentitySigningKeys.arn]:[],parameters=name==='Mem9ProxyFn'?[r.Mem9TransportSigningKeys.arn]:name==='Mem9AlertRouter'?[r.Mem9AlertWebhookParameter.arn]:name==='Mem9OauthFacadeFn'?[r.SsmOauthStateHmacKey.arn,...['/gateway/url','/cognito/reader/client-id','/cognito/reader/client-secret','/oauth/allowed-callback-urls','/slack/signing-secret',...['cluster-name','task-def-arn','task-sg-id','subnet-ids'].map(k=>'/cleanup/'+k),'/approvals/*'].map(p=>ar('ssm','parameter/mem9-on-aws/prod'+p))]:[];const statements=[];for(const [service,action,items,context]of [['secretsmanager','GetSecretValue',secrets,'SecretARN'],['ssm','GetParameters',parameters,'PARAMETER_ARN']])if(items.length){statements.push(allow(service+':'+action,items),{...allow('kms:Decrypt',[key]),Condition:{StringEquals:{'kms:ViaService':service+'.'+region+'.amazonaws.com'},ArnEquals:{['kms:EncryptionContext:'+context]:items}}});}if(name==='Mem9AlertRouter')statements.push(allow('sqs:SendMessage',[r.AlertExecutionFailureQueue.arn]));fn[name].role.inlinePolicies[0].policy=policy(statements);}
 const backend='sg-11111111',proxySg='sg-22222222',endpointSg='sg-33333333',vpc='vpc-11111111',subnets=['subnet-11111111'];
 Object.assign(r.Mem9GatewayProxySg,{id:proxySg,vpcId:vpc,ingress:[],egress:[{protocol:'tcp',fromPort:8080,toPort:8080,securityGroups:[backend]},{protocol:'tcp',fromPort:443,toPort:443,securityGroups:[endpointSg]}]});Object.assign(r.Mem9GatewaySecretEndpointSg,{id:endpointSg,vpcId:vpc,ingress:[],egress:[]});proxy.vpcConfig={subnetIds:subnets,securityGroupIds:[proxySg]};
 for(const [service,name,id,items]of [['ssm','Mem9GatewaySsmEndpoint','vpce-11111111',[r.Mem9TransportSigningKeys.arn]],['secretsmanager','Mem9GatewaySecretsManagerEndpoint','vpce-22222222',[r.Mem9TenantApiKey.arn,r.Mem9IdentitySigningKeys.arn]]]){const dnsName=`${id}-abcdef.${service}.${region}.vpce.amazonaws.com`;Object.assign(r[name],{id,vpcId:vpc,subnetIds:subnets,securityGroupIds:[endpointSg],serviceName:`com.amazonaws.${region}.${service}`,vpcEndpointType:'Interface',privateDnsEnabled:false,ipAddressType:'ipv4',policy:policy([{Effect:'Allow',Principal:{AWS:proxy.role.arn},Action:service==='ssm'?'ssm:GetParameters':'secretsmanager:GetSecretValue',Resource:items}]),dnsEntries:[{dnsName,hostedZoneId:'ZEXAMPLE'}],state:'available'});const prefix=service==='ssm'?'MEM9_SECRET_SSM':'MEM9_SECRET_SECRETSMANAGER';proxy.environment[prefix+'_VPCE_ID']=id;proxy.environment[prefix+'_ENDPOINT_DNS']=dnsName;}
 for(const [name,to,port]of [['Mem9TaskFromProxyLambda',backend,8080],['Mem9GatewaySecretEndpointIngress',endpointSg,443]])Object.assign(r[name],{id:'sgr-11111111',type:'ingress',securityGroupId:to,sourceSecurityGroupId:proxySg,protocol:'tcp',fromPort:port,toPort:port});
 Object.assign(r.Mem9GatewayServiceRole,{name:'mem9-on-aws-prod-gateway-service-role',arn:ar('iam','role/mem9-on-aws-prod-gateway-service-role'),uniqueId:'AROASYNTHETICGATEWAY',assumeRolePolicy:policy([{Effect:'Allow',Action:'sts:AssumeRole',Principal:{Service:'bedrock-agentcore.amazonaws.com'}}]),permissionsBoundary:boundary});Object.assign(r.Mem9GatewayInvokeLambda,{name:'gateway-invoke',role:r.Mem9GatewayServiceRole.name,policy:policy([allow('lambda:InvokeFunction',[proxy.arn,fn.Mem9IdentityInterceptorFn.arn])])});
 Object.assign(r.Mem9Gateway,{gatewayId:'gateway-fixture',gatewayArn:ar('bedrock-agentcore','gateway/gateway-fixture'),gatewayUrl:'https://gateway.example.com/mcp',roleArn:r.Mem9GatewayServiceRole.arn});Object.assign(r.Mem9Discovery,{id:'srv-fixture',arn:ar('servicediscovery','service/srv-fixture'),name:'mnemo-server'});Object.assign(r.Mem9GatewayTarget,{stdout:'new-target-id\n',environment:{MEM9_TGT_REGION:region,MEM9_TGT_GATEWAY_ID:r.Mem9Gateway.gatewayId,MEM9_TGT_NAME:'prod-mem9-rest',MEM9_TGT_LAMBDA_ARN:proxy.arn}});r.Mem9ProxyFnEnvironmentUpdate.environment=Object.fromEntries(Object.entries(proxy.environment).filter(([k])=>k==='MEM9_SECRET_ENDPOINT_MODE'||k.includes('_VPCE_ID')||k.includes('_ENDPOINT_DNS')));
 const before={account,region,proxyArn:proxy.arn,gatewayId:r.Mem9Gateway.gatewayId,gatewayArn:r.Mem9Gateway.gatewayArn,auth:{mode:'managed',gatewayUrl:r.Mem9Gateway.gatewayUrl,tokenEndpoint:fn.Mem9OauthFacadeFn.environment.COGNITO_TOKEN_ENDPOINT},cloudMapServiceId:r.Mem9Discovery.id,cloudMapServiceArn:r.Mem9Discovery.arn,serverBaseUrl:proxy.environment.MEM9_SERVER_BASE_URL,targetName:'prod-mem9-rest',vpcIds:[vpc]};
 const sourceFiles=[],sourceBytes={};for(const path of paths){const raw=sourceBytes[path]=await readFile(join(repo,path));sourceFiles.push({path,mode:'100644',oid:createHash('sha1').update('blob '+raw.length+'\0').update(raw).digest('hex'),sha256:sha(raw)});}
 const value={version:1,kind:'sst-owned-deployment-capture',policyHash:NONROOT_POSTAPPLY_POLICY_HASH,source:source??{repository:'example/repository',runId:77,runAttempt:1,jobKey:'deploy-prod',revision:'a'.repeat(40),tree,grantSetId:'c'.repeat(64),descriptorHash:'d'.repeat(64),proofHash:'e'.repeat(64)},sourceFiles,functions,resources:r,capturedMs:Date.now()-100,completedMs:Date.now()};
 return {value,zips,sourceBytes,expected:{sourceScope:{tree,files:sourceFiles.map(({sha256,...f})=>f),policyHash:NONROOT_POSTAPPLY_POLICY_HASH},before,backendSecurityGroupId:backend,subnetIds:subnets,boundaryArn:boundary,keyArns:[key]},sha,hash};
}
