import {it,expect,beforeAll,afterEach} from 'vitest';
import {mkdtemp,mkdir,writeFile,readFile,rm,symlink,stat} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,dirname} from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {postApplyFixture,sha,repo} from './nonroot-postapply.fixture.mjs';
import {nonrootDeploymentWrapperFixture} from './production-nonroot-deployment.fixture.mjs';
import {nonrootHash as hash} from './lib/production-nonroot-contracts.mjs';
import {NONROOT_REMAINING_WORK_LIMITS_HASH_V2,NONROOT_REMAINING_WORK_CAPS_V2} from './lib/production-nonroot-budget-revision.mjs';
import {NONROOT_POSTAPPLY_LIMITS as L,decodeNonrootPostApplyArtifact,verifyNonrootPostApplyDeployment} from './lib/nonroot-postapply.mjs';
import {writePostApplyCaptureAllocation,captureSstPostApplyOutputs,completeSstPostApplyCapture,readCompletedPostApplyArtifact,postApplyIdentity} from './lib/nonroot-postapply-capture.mjs';
let native;const roots=[];beforeAll(async()=>{native=await nonrootDeploymentWrapperFixture();},60000);afterEach(async()=>{for(const root of roots.splice(0))await rm(root,{recursive:true,force:true});});
const zero=()=>({ecrRequests:0,logicalBytes:0,httpBodyBytes:0,uncompressedBytes:0,processedEntries:0});
async function setup(){
 const root=await mkdtemp(join(tmpdir(),'postapply-'));roots.push(root);const work=join(root,'.sst'),runner=join(root,'runner'),dir=join(runner,'mem9-ci-future-acquisitions');await mkdir(dir,{recursive:true,mode:0o700});
 const d={...structuredClone(native.current),issuedMs:Date.now()-1000,expiresMs:Date.now()+300000},scope={kind:'target',jobKey:'deploy-prod',route:'deploy-prod',phase:'presst',checkpoint:'deploy-prod/19'},postScope={...scope,phase:'preupdate',checkpoint:'deploy-prod/21'},s={repository:'example/repository',prNumber:17,candidateRevision:'a'.repeat(40),candidateTree:d.controlSourceTree,baseRevision:'c'.repeat(40)};
 const config={version:3,kind:'owner-ci-acquisition-config',startup:{version:1,kind:'owner-prepaid-startup-config',grantSetId:'1'.repeat(64),grantHash:'2'.repeat(64),ledgerStartHash:'3'.repeat(64),catalogHash:'4'.repeat(64),descriptorHash:hash(d),proofHash:d.transition.proofHash,source:s,consumers:[scope,postScope],ownerGithubActorId:42,notAfter:Math.min(d.expiresMs,Date.now()+240000)},target:{kind:'production-data-release',descriptor:d,parameterVersion:2},account:d.account,region:d.region,ownerRoot:{runtimeNonce:d.runtimeNonce,authorizationId:d.authorizationId},storage:{bucket:'example-owned-artifacts',kmsKeyArn:`arn:aws:kms:${d.region}:${d.account}:key/00000000-0000-4000-8000-${'0'.repeat(12)}`,bucketKeyEnabled:true},bootstrap:[scope,postScope].map(x=>({checkpoint:x.checkpoint,responseBytes:65536})),budgetRevision:{version:2,limitsHash:NONROOT_REMAINING_WORK_LIMITS_HASH_V2,envelopeHash:hash('envelope'),historyHeadHash:hash('history')},compiledCeiling:NONROOT_REMAINING_WORK_CAPS_V2};
 const binding={source:{repository:s.repository,runId:77,runAttempt:1,mainRevision:'d'.repeat(40),mainTree:s.candidateTree}},env={...process.env,RUNNER_TEMP:runner,GITHUB_ACTIONS:'true',GITHUB_JOB:'deploy-prod',GITHUB_REPOSITORY:s.repository,GITHUB_RUN_ID:'77',GITHUB_RUN_ATTEMPT:'1',GITHUB_SHA:binding.source.mainRevision,GITHUB_WORKFLOW_SHA:binding.source.mainRevision,GITHUB_EVENT_NAME:'push',GITHUB_REF:'refs/heads/main',MEM9_CI_ACQUISITION_CONFIG:JSON.stringify(config)};
 const f=await postApplyFixture({account:d.account,region:d.region,tree:s.candidateTree,source:postApplyIdentity(config,binding)});
 for(const [path,bytes]of Object.entries(f.sourceBytes)){await mkdir(dirname(join(root,path)),{recursive:true});await writeFile(join(root,path),bytes,{mode:0o644});}
 for(const [name,bytes]of Object.entries(f.zips)){await mkdir(join(work,'artifacts',name),{recursive:true});await writeFile(join(work,'artifacts',name,'code.zip'),bytes,{mode:0o600});}
 const prefix='target-'+hash({bindingHash:hash(binding),scope})+'-local-replay-sst',expiresMs=config.startup.notAfter,start={...zero(),logicalBytes:13},claim={version:1,kind:'ci-future-local-replay',scope,startingLocalUsed:start,expiresMs,ownerRefund:0},delta={...zero(),logicalBytes:8},paid={...zero(),logicalBytes:L.captureLocalBytes},localBudget={...zero(),logicalBytes:L.captureLocalBytes+4194304},localUsed={...zero(),logicalBytes:13+8+L.captureLocalBytes};
 const claimBytes=Buffer.from(JSON.stringify(claim)),journal=Buffer.from(JSON.stringify(delta)+'\n'+JSON.stringify(paid)+'\n'),claimRef={path:join(dir,prefix+'-claim.json'),sha256:sha(claimBytes)},localRef={path:join(dir,prefix+'.ndjson'),sha256:sha(journal)};await writeFile(claimRef.path,claimBytes,{mode:0o600});await writeFile(localRef.path,journal,{mode:0o600});
 await writePostApplyCaptureAllocation({env,config,binding,scope,localRef,claimRef,localBudget,localUsed,expiresMs});
 const functions=structuredClone(f.value.functions);for(const fn of Object.values(functions))Object.assign(fn.environment,{SST_KEY:'synthetic-private-sst-key',SST_KEY_FILE:'resource.enc',SST_RESOURCE_App:JSON.stringify({name:'mem9-on-aws',stage:'prod'})});
 return {...f,root,work,env,config,binding,scope,postScope,claimRef,localRef,functions,dir:join(runner,'mem9-nonroot-deployment'),capture(){return captureSstPostApplyOutputs({env,root,work,functions,resources:f.value.resources});}};
}
it('captures actual ZIP/source bytes and completes in a different Node process under one native debit',async()=>{
 const f=await setup(),digest=await f.capture();expect(digest).toMatch(/^[a-f0-9]{64}$/);const output=await readFile(join(f.dir,'sst-output.json'));expect(output.toString()).not.toContain('synthetic-private-sst-key');
 const result=await promisify(execFile)(process.execPath,[join(repo,'scripts/record-nonroot-deployment.mjs'),'complete'],{env:f.env});expect(result.stdout).not.toContain('synthetic-private-sst-key');
 const artifact=await readCompletedPostApplyArtifact({env:f.env,config:f.config,binding:f.binding,scope:f.postScope}),value=decodeNonrootPostApplyArtifact(artifact);expect(value.sourceFiles).toEqual(f.value.sourceFiles);expect(verifyNonrootPostApplyDeployment(value,f.expected).targetId).toBe('new-target-id');
 const capture=JSON.parse(await readFile(join(f.dir,'capture-accounting.json'))),complete=JSON.parse(await readFile(join(f.dir,'complete-accounting.json')));expect(capture.allocatedBytes+complete.allocatedBytes).toBe(L.captureLocalBytes);for(const r of [capture,complete]){expect(r.usedBeforeReceipt).toBe(r.operations.reduce((n,x)=>n+x.bytes,0));expect(r.usedBeforeReceipt).toBeLessThan(r.allocatedBytes);expect(r.operations.filter(x=>x.purpose.endsWith('.ndjson'))).toHaveLength(1);}
 expect((await stat(join(f.dir,'completed.json'))).mode&511).toBe(384);await expect(f.capture()).rejects.toThrow();await expect(completeSstPostApplyCapture(f.env)).rejects.toThrow();
});
it.each(['journal-middle','native-start','native-final','unfunded','zip','symlink','secret','expired','wrong-run'])('rejects %s without a completion artifact',async defect=>{
 const f=await setup();if(defect==='journal-middle')await writeFile(f.localRef.path,(await readFile(f.localRef.path)).toString().replace('8,','9,'));
 if(['native-start','native-final','unfunded'].includes(defect)){const p=join(f.dir,'allocation.json'),a=JSON.parse(await readFile(p));if(defect==='native-start'){const c=JSON.parse(await readFile(f.claimRef.path));c.startingLocalUsed.logicalBytes++;const raw=Buffer.from(JSON.stringify(c));await writeFile(f.claimRef.path,raw);a.claimRef.sha256=sha(raw);}if(defect==='native-final')a.localUsed.logicalBytes--;if(defect==='unfunded')a.localBudget.logicalBytes=L.captureLocalBytes-1;await writeFile(p,JSON.stringify(a));}
 if(defect==='zip')await writeFile(join(f.work,'artifacts','Mem9ProxyFn','code.zip'),'corrupt');if(defect==='symlink'){const p=join(f.work,'artifacts','Mem9ProxyFn','code.zip');await rm(p);await symlink(join(f.work,'artifacts','Mem9AlertRouter','code.zip'),p);}if(defect==='secret')f.functions.Mem9ProxyFn.environment.AWS_SECRET_ACCESS_KEY='never-retain';
 if(defect==='expired'){const p=join(f.dir,'allocation.json'),a=JSON.parse(await readFile(p));a.expiresMs=1;await writeFile(p,JSON.stringify(a));}if(defect==='wrong-run')f.env.GITHUB_RUN_ATTEMPT='2';
 await expect(f.capture()).rejects.toThrow();await expect(readFile(join(f.dir,'completed.json'))).rejects.toThrow();
});
it('partial apply cannot complete and a failed completion cannot restart',async()=>{const f=await setup();await expect(completeSstPostApplyCapture(f.env)).rejects.toThrow();await f.capture();await expect(completeSstPostApplyCapture(f.env)).rejects.toThrow();});
it('normal capture exhaustion cannot consume completion headroom or renew payment',async()=>{const f=await setup();for(const [name,bytes]of Object.entries(f.zips)){const raw=Buffer.alloc(L.zipBytes);bytes.copy(raw);const p=join(f.work,'artifacts',name,'code.zip');await writeFile(p,raw);const hash=sha(raw);Object.assign(f.functions[name],{codeSha256:Buffer.from(hash,'hex').toString('base64'),s3Key:`assets/${name}-code-${hash}.zip`});}await expect(f.capture()).rejects.toThrow('PostApplyLocalBudget');await expect(readFile(join(f.dir,'sst-output.json'))).rejects.toThrow();await expect(f.capture()).rejects.toThrow();});
