import {createHash} from 'node:crypto';
import {deflateRawSync} from 'node:zlib';
import {imageTransitionFixture} from './production-image-transition.fixture.mjs';
import {transitionFixture} from './production-canary-transition.fixture.mjs';
import {tar} from './production-image.fixture.mjs';
import {stringify as yaml} from 'yaml';
import {describeDataBuildInputs} from './lib/production-data-build-inputs.mjs';
import {NONROOT_LIMITS,NONROOT_HARDENING_POLICY,NONROOT_GUARD_BUILTINS,inspectNonrootRecord,nonrootHash as hash} from './lib/production-nonroot-contracts.mjs';
import {createNonrootEvidenceArchive} from './lib/production-nonroot-archive.mjs';
import {inspectImageCopyVerification} from './lib/production-image-graph.mjs';
import {inspectImageFilesystem,inspectImageFilesystemEvidence,inspectImageFilesystemEntries} from './lib/production-image-filesystem.mjs';
import {controlLaunchPolicy,dataLaunchPolicy,resolveCarrierRunTaskRequest,NONROOT_FORBIDDEN_ENVIRONMENT} from './lib/production-nonroot-launch.mjs';
import {NONROOT_DEPLOYED_CONTROL_IMAGE_SLOT} from './lib/production-nonroot-provenance.mjs';

const sha=b=>createHash('sha256').update(b).digest('hex'),h=label=>sha('synthetic:'+label),g=label=>h(label).slice(0,40),n=label=>h(label).slice(0,32);
const COMPONENTS=['llm-proxy','mnemo-server','qwen3-embed'];
function executableTar(entries){
 const result=tar(entries);let offset=0;
 for(const entry of entries){const header=result.subarray(offset,offset+512),size=Buffer.byteLength(entry.body??'');header.write((entry.mode??0o755).toString(8).padStart(7,'0')+'\0',100);header.fill(32,148,156);let sum=0;for(const byte of header)sum+=byte;header.write(sum.toString(8).padStart(6,'0')+'\0 ',148);offset+=512+Math.ceil(size/512)*512;}
 return result;
}
export function nonrootArchiveFixture(owner){
 const objects=new Map(),files=[],byBytes=new Map();
 const add=(bytes,encoding,purpose,name)=>{
  bytes=Buffer.from(bytes);const key=encoding+':'+sha(bytes);if(byBytes.has(key))return byBytes.get(key);
  const ref=encoding==='json'?{bytesHash:sha(bytes),canonicalHash:hash(JSON.parse(bytes.toString())),bytesLength:bytes.length}:{sha256:sha(bytes),bytesLength:bytes.length};
  name??='sha256-'+sha(bytes)+(encoding==='json'?'.json':'.bin');objects.set(name,bytes);files.push({name,purpose,ref,encoding});byBytes.set(key,ref);return ref;
 };
 const json=(value,purpose='source',name)=>add(JSON.stringify(value)+'\n','json',purpose,name),bytes=(value,purpose='source',name)=>add(value,'bytes',purpose,name);
 const manifest=()=>({version:2,kind:'nonroot-proof-archive',owner,files:structuredClone(files)});
 const archive=()=>createNonrootEvidenceArchive(JSON.stringify(manifest()),{expectedManifestHash:hash(manifest()),readObject:async name=>objects.get(name)});
 const value=ref=>JSON.parse(objects.get(files.find(f=>hash(f.ref)===hash(ref)).name).toString());
 const replaceJson=(name,value)=>{
  const row=files.find(f=>f.name===name);if(!row||row.encoding!=='json')throw Error('FixtureRecordMissing');
  byBytes.delete('json:'+row.ref.bytesHash);const raw=Buffer.from(JSON.stringify(value)+'\n');
  row.ref={bytesHash:sha(raw),canonicalHash:hash(value),bytesLength:raw.length};objects.set(name,raw);byBytes.set('json:'+row.ref.bytesHash,row.ref);return row.ref;
 };
 return {objects,files,json,bytes,manifest,archive,value,replaceJson};
}

/** Synthetic metadata/service replies only. The graph and package filesystem
 * contexts are produced by the actual byte verifiers, not JSON approval flags. */
export async function nonrootProofFixture({controlSourceTree,controlSourceFiles}={}){
 const imageConfigurations=Object.fromEntries(COMPONENTS.map(name=>[name,{Entrypoint:name==='mnemo-server'?['/usr/local/bin/entrypoint.sh']:['node','server.mjs'],Cmd:[],WorkingDir:'/app',Env:['PATH=/usr/local/bin:/usr/bin:/bin']}]));
 const layerBytes=Object.fromEntries(COMPONENTS.map(name=>[name,executableTar([
  ...['bin','usr','usr/bin','usr/local','usr/local/bin','app','tmp'].map(path=>({path,type:'5',mode:path==='tmp'?0o1777:0o755})),
  {path:'usr/local/bin/node',body:'synthetic node executable'},
  ...(name==='mnemo-server'?[{path:'bin/busybox',body:'synthetic busybox executable'},{path:'bin/setpriv',type:'2',link:'busybox'},{path:'usr/local/bin/entrypoint.sh',body:'exec synthetic-mnemo'},{path:'lib/apk/db/installed',body:'P:zlib\nV:1.3.2-r1\nA:aarch64\n\n',mode:0o644}]:[{path:'usr/bin/setpriv',body:'synthetic setpriv executable'},{path:'app/server.mjs',body:'export const synthetic=true;',mode:0o644}]),
 ])]));
 const f=await imageTransitionFixture({rootCounters:{changedRows:6,receipts:3},observationNow:transitionFixture().now+7200000,layerBytes,imageConfigurations,workerContainerNames:{planner:'Mem9ConsolidationPlanner',executor:'Mem9ConsolidationExecutor'}}),owner=n('owner'),a=nonrootArchiveFixture(owner),{json,bytes}=a,now=f.now;
 const account=f.predecessor.account,region=f.predecessor.region,cluster=f.legacy.current.network.cluster,family=cluster.split('/').at(-1)+'-ControlMem9Bootstrap';
 const role=name=>`arn:aws:iam::${account}:role/example-${name}`,td=`arn:aws:ecs:${region}:${account}:task-definition/${family}:7`,task=`arn:aws:ecs:${region}:${account}:task/${cluster.split('/').at(-1)}/${n('carrier-task')}`;
 const copy=inspectImageCopyVerification(f.graphVerification),fs=inspectImageFilesystemEvidence(f.filesystemVerification),filesystems={};
 for(const name of COMPONENTS)filesystems[name]=name==='mnemo-server'?f.filesystemVerification:await inspectImageFilesystem(f.native.destinationGraph,{component:name});
 const images=Object.fromEntries(COMPONENTS.map(name=>[name,{...f.images[name],configDigest:JSON.parse(JSON.parse(f.input.artifacts[name].child).images[0].imageManifest).config.digest}]));
 const leaf=label=>json({version:1,kind:'synthetic-'+label});
 const sourceFile=(path,body)=>({path,gitMode:'100644',sha256:sha(body),bytes:Buffer.byteLength(body),blob:bytes(body)});
 const closure=(tree,files)=>({version:1,kind:'git-file-closure',tree,files,closureHash:hash(files)});
 const controlSource={...f.input.control.sourceEvidence,...(controlSourceTree?{controlTree:controlSourceTree}:{}),preview:{runId:'101',attempt:1},rehearsal:{runId:'102',attempt:1}};
 const deploymentControl={revision:f.input.control.revision,tree:controlSourceTree??f.input.control.sourceTree,baseRevision:f.input.control.baseRevision,sourceEvidence:json(controlSource,'source','source-evidence.json')};
 const originEvidence={...f.input.dataOrigin.sourceEvidence,preview:{runId:'103',attempt:1}};
 const dataOrigin={revision:f.input.dataOrigin.revision,tree:f.input.dataOrigin.sourceTree,sourceHead:f.input.dataOrigin.sourceHead,sourceEvidence:json(originEvidence),buildCommit:json(f.input.dataOrigin.buildCommit),
  buildRun:json({id:103,run_attempt:1,event:'pull_request',status:'completed',conclusion:'success',head_sha:f.input.dataOrigin.sourceHead,path:'.github/workflows/infra-ci.yml',head_repository:{full_name:controlSource.repository}}),
  buildJobs:json({total_count:1,jobs:[{id:104,run_id:103,run_attempt:1,name:'Build & push workload images',status:'completed',conclusion:'success'}]}),buildLog:bytes(f.input.buildEvidence.logText,'build'),recipeHash:hash(f.input.dataInputs.recipe),images};
 const root={stage:'prod',account,region,runtimeNonce:f.predecessor.runtimeNonce,schemaDigest:f.predecessor.schemaDigest,operatorDigest:f.predecessor.operatorDigest,rootIdentity:h('root'),generation:f.legacy.parent.generation,validationId:f.legacy.parent.validationId,targetsHash:f.predecessor.targetsHash,parentProofHash:hash(f.legacy.parent),originalBackendBindingHash:f.legacy.parent.backendBindingHash,originalReleaseHash:f.legacy.parent.releaseHash,plannerOid:101,executorOid:102,protectedBaselineHash:h('protected'),protectedRows:100,receipts:f.legacy.parent.receipts,receiptSetHash:f.legacy.parent.replayResultHash,conservationHash:f.legacy.parent.conservationHash,spent:f.legacy.parent.changedRows,cap:20};
 const parameter={Name:'/mem9-on-aws/prod/consolidation-runtime/data-release',ARN:`arn:aws:ssm:${region}:${account}:parameter/mem9-on-aws/prod/consolidation-runtime/data-release`,Type:'SecureString',Version:f.legacy.current.dataRelease.parameterVersion,Value:JSON.stringify(f.predecessor)};
 const predecessorParameter=json(parameter,'protocol','predecessor.json'),legacyBootstrapProof=json({version:1,kind:'verified-legacy-bootstrap-inputs',proof:f.input.bootstrapProof,expectedBootstrap:f.expected.expectedBootstrap},'protocol','legacy-bootstrap-proof.json');
 const old=f.legacy.previous,release={sourceTree:old.sourceTree,coordinatorDigest:old.coordinatorDigest,sourceTag:old.sourceTag,workerImage:old.workerImage,...old.runtime};
 const oldCertificate=json({version:2,dataReleaseHash:h('baseline-descriptor'),parentProofHash:root.parentProofHash,generation:root.generation,targetsHash:root.targetsHash,previous:{release,backendBindingHash:root.originalBackendBindingHash},current:{release,backendBinding:old.backendBinding},images:Object.fromEntries(['worker',...COMPONENTS].map(name=>[name,{previousRoot:old.components[name].rootDigest,currentRoot:old.components[name].rootDigest,previousChild:old.components[name].arm64Digest,currentChild:old.components[name].arm64Digest}])),material:Object.fromEntries(Object.entries(old.material).map(([name,digest])=>[name,{previous:digest,current:digest}]))},'root-audit');
 const graph=json({version:1,graphHash:copy.graphHash,summary:copy.summary,inventory:copy.inventory,destinationReadback:copy.destinationReadback},'image-graph');
 const copyControl={revision:g('copy-control'),tree:g('copy-tree'),baseRevision:g('copy-base'),sourceEvidence:leaf('historical-copy-source')};
 const historicalCopy={version:1,kind:'historical-copy-adoption',owner:n('old-copy'),control:copyControl,stageConfig:leaf('stage-config'),initialJournal:leaf('initial-journal'),recoveryDesign:leaf('recovery-design'),recoveryReviews:leaf('recovery-reviews'),recoverySource:leaf('recovery-source'),recoveryTerminal:json({version:1,owner:n('old-copy'),completed:true,cleanupComplete:true,hold:false}),completedGraph:graph,destinationReadback:json(copy.destinationReadback,'image-graph'),originalVerifierClosure:leaf('old-verifier'),cumulativeBudget:leaf('cumulative-budget'),oldIdDenial:leaf('denied-ids')};
 json(historicalCopy,'protocol','copy-adoption.json');
 const entries=Object.fromEntries(COMPONENTS.map(name=>[name,inspectImageFilesystemEntries(filesystems[name])]));
 const primitives=Object.fromEntries(COMPONENTS.map(name=>{const path=name==='mnemo-server'?'/bin/setpriv':'/usr/bin/setpriv',resolvedPath=name==='mnemo-server'?'/bin/busybox':path,node=entries[name].find(e=>e.path===resolvedPath.slice(1));return [name,{version:1,kind:'verified-nnp-primitive',image:images[name],invokedPath:path,resolvedPath,fileSha256:node.content.sha256,mode:493,uid:0,gid:0,symlinkChain:json(name==='mnemo-server'?[{path:'/bin/setpriv',target:'/bin/busybox'}]:[]),loaderAndLibraries:json({files:[]}),privilegeMetadata:json({setuid:false,setgid:false,fileCapabilities:false}),featureProbe:json({image:images[name],executableSha256:node.content.sha256,noNewPrivs:1,exitCode:0}),inheritanceAndNegativeProbes:json({image:images[name],executableSha256:node.content.sha256,setuidBlocked:true,setgidBlocked:true,clearRejected:true})}];}));
 const artifactReverification={version:1,kind:'readonly-artifact-reverification',copyRecordHash:hash(historicalCopy),verifierClosure:leaf('new-verifier'),graph,destinationReadback:historicalCopy.destinationReadback,filesystem:json({version:1,evidence:Object.fromEntries(COMPONENTS.map(name=>[name,inspectImageFilesystemEvidence(filesystems[name])])),filesystem:f.input.filesystem},'filesystem'),imageConfigs:json(Object.fromEntries(COMPONENTS.map(name=>[name,{image:images[name],config:bytes(f.native.data.get(images[name].configDigest),'image-graph')}])),'image-graph'),pathPermissions:json(entries,'filesystem'),primitiveEvidence:json(primitives,'filesystem'),contentHash:copy.summary.contentHash,startedMs:copy.summary.startedMs,completedMs:copy.summary.completedMs,readAccounting:json({calls:12,bytes:4096})};
 json(artifactReverification,'protocol','artifact-reverification.json');
 const carrierConfig=bytes(JSON.stringify({architecture:'arm64',os:'linux',config:{Env:[]}}),'image-graph');
 const child=bytes(JSON.stringify({schemaVersion:2,mediaType:'application/vnd.oci.image.manifest.v1+json',config:{digest:'sha256:'+carrierConfig.sha256,size:carrierConfig.bytesLength,mediaType:'application/vnd.oci.image.config.v1+json'},layers:[]}),'image-graph');
 const index=bytes(JSON.stringify({schemaVersion:2,mediaType:'application/vnd.oci.image.index.v1+json',manifests:[{digest:'sha256:'+child.sha256,size:child.bytesLength,mediaType:'application/vnd.oci.image.manifest.v1+json',platform:{os:'linux',architecture:'arm64'}}]}),'image-graph');
 const carrierImage={account,region,repositoryName:'mem9-on-aws/preview/bootstrap',rootDigest:'sha256:'+index.sha256,arm64Digest:'sha256:'+child.sha256,configDigest:'sha256:'+carrierConfig.sha256},imageOnly=({rootDigest,arm64Digest,configDigest})=>({rootDigest,arm64Digest,configDigest});
 const guardSource=closure(deploymentControl.tree,[sourceFile('docker/bootstrap/nonroot-dispatch.mjs','export const synthetic=true;')]);
 const nodeRuntime={version:1,kind:'pinned-node-runtime',versionString:'24.1.0',executablePath:'/usr/local/bin/node',executableSha256:h('node'),loaderAndNativeLibraries:leaf('node-libraries'),image:imageOnly(carrierImage),inventory:leaf('node-inventory')};
 const guardImports={version:1,kind:'minimal-guard-imports',entryModule:guardSource.files[0].blob,localGuardFiles:guardSource,allowedBuiltins:NONROOT_GUARD_BUILTINS,policyHash:h('guard-policy'),importAudit:leaf('guard-audit'),nodeRuntime};
 const legacyCode=bytes('export const syntheticLegacyRootAudit=true;');
 const logicalInvocation={nodeMode:'esm-file',legacyProgramPath:'/carrier/legacy-audit.mjs',logicalArgv:['/usr/local/bin/node','/carrier/legacy-audit.mjs'],inputEncoding:'deflate-raw-base64',inputSchemaSource:bytes('synthetic input schema'),maximumDecodedInputBytes:32768,requiredEnvironmentNames:['MEM9_SUPERSESSION_ROOT_INPUT','MEM9_SUPERSESSION_ROOT_HASH','MEM9_SUPERSESSION_ROOT_CODE_HASH'],executionTest:leaf('legacy-execution')};
 const legacyFiles=[{sourceKind:'host',role:'audit-program',sourcePath:'/original/audit.mjs',destinationPath:'/carrier/legacy-audit.mjs',sourceBytes:legacyCode,destinationBytes:legacyCode,sourceMetadata:leaf('source-metadata'),destinationMetadata:leaf('destination-metadata'),sourceEvidence:leaf('legacy-source'),destinationEvidence:leaf('legacy-destination')}];
 const legacyClosureProof={version:1,kind:'byte-authenticated-legacy-closure',hostOrigin:{kind:'historical-host-audit',authenticatedArchiveAnchor:leaf('legacy-anchor'),sourceFiles:leaf('legacy-files'),historicalInvocation:leaf('legacy-invocation'),priorReview:leaf('legacy-review'),exactCode:legacyCode,expandedSource:legacyCode,codeHash:legacyCode.sha256,sourceHash:legacyCode.sha256},imageOrigin:{kind:'historical-deployed-control',deployedBinding:leaf('old-control-binding'),source:copyControl,buildEvidence:leaf('old-control-build'),image:{...carrierImage,repositoryName:'mem9-on-aws/bootstrap'},imageGraph:leaf('old-control-graph'),effectiveFilesystem:leaf('old-control-filesystem')},files:legacyFiles,closureInventory:json(legacyFiles),sourceBundle:bytes('synthetic source bundle'),destinationImage:carrierImage,destinationFilesystem:leaf('carrier-filesystem'),logicalInvocation,sourceClosureHash:hash(legacyFiles),destinationClosureHash:hash(legacyFiles),verifiedMs:now-20000};
 const carrierSource={repository:controlSource.repository,revision:deploymentControl.revision,tree:deploymentControl.tree,baseRevision:deploymentControl.baseRevision,prNumber:controlSource.prNumber,sourceEvidence:deploymentControl.sourceEvidence};
 const carrierBuild={version:1,kind:'premerge-audit-carrier',source:carrierSource,build:{revision:deploymentControl.revision,tree:deploymentControl.tree,workflowPath:'.github/workflows/infra-ci.yml',runId:105,attempt:1,jobId:106,evidence:leaf('carrier-build')},image:carrierImage,secureBase:leaf('carrier-base'),legacyClosureProof,guard:{path:'/carrier/guard-first.mjs',sha256:h('guard-first'),closure:json(guardSource)},entryPoint:controlLaunchPolicy('audit-original-root').entryPoint,command:[],primitiveEvidence:leaf('carrier-primitive'),guardImports,codeReview:leaf('carrier-code-review'),artifactSecurity:leaf('carrier-security'),syntheticTests:leaf('carrier-tests'),completedMs:now-15000};
 json(carrierBuild,'protocol','carrier-build.json');
 const registration={family,networkMode:'awsvpc',requiresCompatibilities:['FARGATE'],runtimePlatform:{cpuArchitecture:'ARM64',operatingSystemFamily:'LINUX'},cpu:'256',memory:'512',taskRoleArn:role('task'),executionRoleArn:role('execution'),containerDefinitions:[{...controlLaunchPolicy('audit-original-root',{name:'ControlMem9Bootstrap',environment:[],secrets:[],linuxParameters:{initProcessEnabled:true}}),image:`${account}.dkr.ecr.${region}.amazonaws.com/mem9-on-aws/preview/bootstrap@${carrierImage.rootDigest}`}]};
 const registrationBody=json(registration,'task-definition'),networkConfiguration={awsvpcConfiguration:{subnets:['subnet-aaaaaaaa'],securityGroups:['sg-aaaaaaaa'],assignPublicIp:'DISABLED'}};
 const envGate=overrides=>({version:1,kind:'prelaunch-environment-gate',image:imageOnly(carrierImage),registrationBodyHash:hash(registration),overrideHash:hash(overrides),forbiddenNamesHash:hash({names:NONROOT_FORBIDDEN_ENVIRONMENT,prefix:'LD_'}),imageEnvironment:json([]),taskEnvironment:json([]),secretNamesAndReferences:json([]),overrideEnvironment:json(overrides),loaderFileEvidence:json([]),caBindings:[],checkedMs:now-10000,result:'pass'});
 const runTaskContract={version:1,kind:'carrier-runtask-contract',cluster,count:1,launchType:'FARGATE',platformVersion:'1.4.0',networkConfiguration,enableExecuteCommand:false,enableECSManagedTags:false,propagateTags:'NONE',tags:[{key:'mem9-supersession-owner',value:owner}],taskDefinitionSource:'exact-carrier-registration-readback',clientTokenSource:'permit-invocation',startedByRule:'root-prefix-invocation-first-29',overridesSource:'exact-carrier-overrides'};
 const platform={version:1,kind:'actual-runtime-platform',taskArn:task,taskDefinitionArn:td,launchType:'FARGATE',platformVersion:'1.4.0',platformFamily:'Linux',cpuArchitecture:'ARM64',operatingSystemFamily:'LINUX',rawTask:json({taskArn:task,taskDefinitionArn:td,platformVersion:'1.4.0',platformFamily:'Linux'}),rawDefinition:json({...registration,taskDefinitionArn:td,status:'ACTIVE'}),independentHealthProbe:leaf('carrier-health'),observedMs:now-12000};
 const plan={version:1,kind:'standalone-preaudit-launch-plan',owner,account,region,carrierBuildHash:hash(carrierBuild),legacyClosureProofHash:hash(legacyClosureProof),guardImportsHash:hash(guardImports),environmentPolicyHash:guardImports.policyHash,carrierImage,existingControlBinding:leaf('existing-control'),registrationBody,containerName:'ControlMem9Bootstrap',entryPoint:carrierBuild.entryPoint,command:[],taskRoleArn:role('task'),executionRoleArn:role('execution'),network:json(networkConfiguration),secretNamesAndReferences:json([]),logDestination:leaf('carrier-logs'),environmentGate:envGate({}),maxRuntimeMs:140000,cleanupReserveMs:30000,runTaskContract,carrierPlatform:platform};
 const permissions={version:1,kind:'existing-permissions-preflight',account,applicationRegion:region,iamRegion:'us-west-2',caller:json({Arn:role('caller'),Account:account}),actorBindings:leaf('actor-bindings'),identityPolicies:leaf('identity-policies'),boundaries:leaf('boundaries'),trustAndResourcePolicies:leaf('trust'),organizationAndEndpointControls:leaf('organization-controls'),actionMatrix:leaf('action-matrix'),positiveNegativeTests:leaf('permission-tests'),analyzerScannerReview:leaf('analyzer-review'),carrierRunTaskContractHash:hash(runTaskContract),observedMs:now-12000,result:'pass'};
 json(permissions,'protocol','permissions.json');
 const designReview=json({version:1,kind:'synthetic-design-review',sourceTree:deploymentControl.tree},'protocol','design-review.json');
 const prerequisite={version:1,kind:'premerge-carrier-prerequisite-review',decision:'pass-for-preaudit',designReviewHash:designReview.canonicalHash,carrierBuildHash:hash(carrierBuild),sourceEvidenceHash:deploymentControl.sourceEvidence.canonicalHash,launchPlanHash:hash(plan),permissionsHash:hash(permissions),legacyBindingsHash:hash(legacyClosureProof),reviewedMs:now-11000,expiresMs:now+600000};
 const prerequisiteRef=json(prerequisite,'protocol','carrier-prerequisite-review.json');
 const readback={version:1,kind:'exact-carrier-registration-readback',taskDefinitionArn:td,carrierImage,requestedRegistrationBodyHash:hash(registration),rawDefinition:platform.rawDefinition,rawDefinitionHash:platform.rawDefinition.bytesHash,observedMs:now-10000};
 const invocation=n('invocation'),auditInput={invocation,rootBindingHash:hash(root),oldCertificateHash:oldCertificate.canonicalHash};
 const inputBytes=Buffer.from(JSON.stringify(auditInput)),runOverrides={containerOverrides:[{name:'ControlMem9Bootstrap',environment:[{name:'MEM9_SUPERSESSION_ROOT_INPUT',value:deflateRawSync(inputBytes).toString('base64')},{name:'MEM9_SUPERSESSION_ROOT_HASH',value:sha(inputBytes)},{name:'MEM9_SUPERSESSION_ROOT_CODE_HASH',value:legacyCode.sha256}]}]};
 const presence={version:1,kind:'same-carrier-registry-presence',carrierBuildHash:hash(carrierBuild),image:carrierImage,rootManifest:index,arm64Manifest:child,config:carrierConfig,blobAvailability:leaf('carrier-blobs'),registryObservation:leaf('carrier-presence'),observedMs:now-9000,expiresMs:now+240000},environmentGate={...envGate(runOverrides),checkedMs:now-9000};
 const request=resolveCarrierRunTaskRequest(plan,readback,{invocation,runOverrides});
 const binding={version:1,kind:'permit-bound-carrier-runtask',request,requestHash:hash(request),launchPlanHash:hash(plan),runTaskContractHash:hash(runTaskContract),registrationReadbackHash:hash(readback),environmentGateHash:hash(environmentGate),carrierPresenceHash:hash(presence),authorization:{permissionsDossierHash:hash(permissions),requestHash:hash(request),callerArn:role('caller'),action:'ecs:RunTask',taskDefinitionArn:td,clusterArn:cluster,taskRoleArn:role('task'),executionRoleArn:role('execution'),decision:'allowed'}};
 const permit={version:1,kind:'premerge-readonly-audit-permit',owner,invocation,carrierBuildHash:hash(carrierBuild),prerequisiteReviewHash:prerequisiteRef.canonicalHash,permissionsHash:hash(permissions),launchPlanHash:hash(plan),rootBindingHash:hash(root),predecessorParameterHash:predecessorParameter.canonicalHash,oldCertificateHash:oldCertificate.canonicalHash,oldAuditInputHash:sha(inputBytes),registrationReadback:readback,runOverrides,environmentGate,carrierPresence:presence,runTask:binding,issuedMs:now-8000,deadlineMs:now+240000};
 json(permit,'protocol','preaudit-permit.json');json(plan,'carrier');
 const process={pid:7,ppid:1,startTimeTicks:100,executablePath:'/usr/local/bin/node',executableDigest:'sha256:'+nodeRuntime.executableSha256,entrypointIdentityHash:h('legacy-entrypoint'),uid:[1000,1000,1000,1000],gid:[1000,1000,1000,1000],groups:[],capInh:'0000000000000000',capPrm:'0000000000000000',capEff:'0000000000000000',capBnd:'0000000000000000',capAmb:'0000000000000000',noNewPrivs:1};
 const carrierIdentity={version:2,kind:'application-process-identity',phase:'preaudit',taskKey:'preaudit',account,region,taskArn:task,taskDefinitionArn:td,containerName:'ControlMem9Bootstrap',runtimeId:'carrier-runtime',image:imageOnly(carrierImage),registrationHash:hash(registration),launchContractHash:hash(plan),sourceBindingHash:hash({carrierBuildHash:hash(carrierBuild),preauditPermitHash:hash(permit)}),artifactBinding:{kind:'carrier',carrierBuildHash:hash(carrierBuild),preauditPermitHash:hash(permit),launchPlanHash:hash(plan)},collectorCodeHash:h('collector'),sessionBinding:json({taskArn:task,invocation}),startedMs:now-6000,completedMs:now-2000,application:[process],trustedLaunch:[],managed:[],samples:json([process]),coverage:json({main:process}),result:'pass'};
 const predeploymentAudit={version:2,kind:'old-root-readonly-audit',phase:'predeployment',root,predecessorParameter,oldMaterial:json(f.legacy.current,'root-audit'),oldCertificate,carrierBuild,preauditPermit:permit,taskObservation:json({taskArn:task,taskDefinitionArn:td,lastStatus:'STOPPED',containers:[{name:'ControlMem9Bootstrap',exitCode:0}]}),carrierIdentity,targetJoin:{kind:'not-applicable'},runtimeState:json({phase:'complete',status:'running',root}),extensionMaintenance:leaf('extension-maintenance'),schedulerState:json({executionEnabled:false,dispatcherEnabled:false,enabledSchedules:0}),credentialBindings:leaf('credentials'),writerCensus:json({activeWorkers:0,activeContinuations:0,activeAdministration:0,benchmarkRemaining:0}),ownershipFence:json({owner,invocation}),startedMs:now-7000,databaseObservedMs:now-5000,cloudObservedMs:now-3000,completedMs:now-1000,cleanupComplete:true};
 json(predeploymentAudit,'protocol','predeployment-root-audit.json');
 const dataFiles=new Map(),steps=['setup-buildx-action','setup-qemu-action'].map(name=>({uses:'docker/'+name+'@'+g(name)}));
 for(const name of COMPONENTS){dataFiles.set('docker/'+name+'/Dockerfile','FROM node:24 AS runtime\nCOPY docker/'+name+'/package*.json ./\nCOPY scripts/shared/ /app/\n');dataFiles.set('docker/'+name+'/package.json','{}');dataFiles.set('docker/'+name+'/package-lock.json','{"lock":1}');steps.push({uses:'docker/build-push-action@'+g('build'),with:{context:'.',file:'docker/'+name+'/Dockerfile',platforms:'linux/arm64',pull:true,'no-cache-filters':name==='mnemo-server'?'builder,runtime':'runtime',tags:'same-declared-expression'}});}
 dataFiles.set('scripts/shared/code.mjs','export const value=1;');dataFiles.set('.github/workflows/infra-ci.yml',yaml({jobs:{'build-and-push-image':{steps}}}));
 const sourceFiles=[...dataFiles].sort(([a],[b])=>a.localeCompare(b)).map(([path,body])=>sourceFile(path,body));
 const blobs=new Map(),treeEntries=sourceFiles.map(file=>{const raw=Buffer.from(dataFiles.get(file.path)),oid=createHash('sha1').update('blob '+raw.length+'\0').update(raw).digest('hex');blobs.set(oid,raw);return {path:file.path,mode:file.gitMode,type:'blob',oid};});
 const recipe=await describeDataBuildInputs(treeEntries,async oid=>blobs.get(oid));
 dataOrigin.recipeHash=hash(recipe);json(dataOrigin,'protocol','data-origin.json');
 const currentFiles=controlSourceFiles?[...controlSourceFiles].sort(([a],[b])=>a.localeCompare(b)).map(([path,body])=>sourceFile(path,body)):sourceFiles;
 const protectedFiles=sourceFiles.filter(file=>!controlSourceFiles||file.path!=='.github/workflows/infra-ci.yml');
 const dataInputs={version:1,recipe,controlRecipe:recipe,protectedInputs:protectedFiles.map(({path,sha256})=>({path,sha256})),controlProtectedInputs:protectedFiles.map(({path,sha256})=>({path,sha256}))};
 const protectedInputs=json({version:1,dataInputs,dataClosure:closure(dataOrigin.tree,sourceFiles),controlClosure:closure(deploymentControl.tree,currentFiles)},'protocol','protected-inputs.json');
 const artifactSecurity=json({version:1,kind:'nonroot-artifact-security',artifacts:f.input.artifacts,scans:f.input.scans,policy:f.input.policy,vendors:f.input.vendors,buildEvidence:f.input.buildEvidence},'protocol','artifact-security.json'),policySources=json(f.input.policy.policySources,'protocol','policy-sources.json');
 return {f,a,now,owner,account,region,cluster,root,parameter,predecessorParameter,legacyBootstrapProof,deploymentControl,dataOrigin,historicalCopy,artifactReverification,carrierBuild,plan,permissions,prerequisite,permit,predeploymentAudit,protectedInputs,artifactSecurity,policySources,designReview,guardSource,guardImports,leaf,json,bytes,images,primitives,entries,filesystems,imageConfigurations,dataInputs,hash,sha,h,g,n};
}

export async function completeNonrootProofFixture(options){
 const x=await nonrootProofFixture(options),{f,a,json,bytes,leaf,hash,h,g,now,images,root,carrierBuild,deploymentControl,guardSource,guardImports}=x;
 const slot=NONROOT_DEPLOYED_CONTROL_IMAGE_SLOT,tasks=[],dataLaunches=[],controlLaunches=[],fieldChanges=[],before={},target={};
 const sourceFile=(path,body)=>({path,gitMode:'100644',sha256:sha(body),bytes:Buffer.byteLength(body),blob:bytes(body)});
 const closure=(tree,files)=>({version:1,kind:'git-file-closure',tree,files,closureHash:hash(files)});
 const previewEvidence=leaf('task-preview');
 const registration=value=>{const d=structuredClone(value);for(const k of ['taskDefinitionArn','revision','registeredAt','registeredBy','deregisteredAt','deleteRequestedAt','status','requiresAttributes','compatibilities'])delete d[k];return d;};
 const get=(v,path)=>path.split('.').reduce((a,k)=>a?.[k],v),presence=v=>v===undefined?{present:false}:{present:true,value:v};
 const imageUri=name=>`${x.account}.dkr.ecr.${x.region}.amazonaws.com/mem9-on-aws/${name}@${images[name].rootDigest}`;
 const addChanges=(key,old,next)=>{for(const c of next.containerDefinitions){const prior=old.containerDefinitions.find(v=>v.name===c.name);for(const field of ['user','linuxParameters.capabilities','entryPoint','command','healthCheck.command','image']){
  const left=get(prior,field),right=get(c,field);if(JSON.stringify(left)===JSON.stringify(right))continue;
  fieldChanges.push({taskKey:key,surface:'container',selector:c.name,field,before:presence(left),after:presence(right),cause:field==='user'?'fixed-user':field==='linuxParameters.capabilities'?'drop-all':field==='healthCheck.command'?'fixed-health-nnp':['backend','planner','executor'].includes(key)?field==='image'?'retained-data-image':'fixed-data-nnp':'guarded-control',observationHash:previewEvidence.canonicalHash});
 }}};
 for(const key of ['backend','planner','executor']){
  const raw=structuredClone(f.legacy.current.definitions[key]),old=registration(raw),next=structuredClone(old);
  for(let i=0;i<old.containerDefinitions.length;i++){
   const c=old.containerDefinitions[i],component=key==='backend'?c.name:'llm-proxy',policyKey=key==='backend'?component:key;
   // Fixtures spell out the effective original launch represented by image defaults.
   c.entryPoint=key==='backend'?x.imageConfigurations[component].Entrypoint:['node'];c.command=key==='backend'?[]:['/app/scripts/consolidation-worker.mjs'];
   const hardened=structuredClone(dataLaunchPolicy(policyKey,c));hardened.image=imageUri(component);next.containerDefinitions[i]=hardened;
   dataLaunches.push({version:1,kind:'fixed-data-nnp-launch',taskKey:key,containerName:c.name,image:images[component],originalEntryPoint:c.entryPoint,originalCommand:c.command,prefix:[component==='mnemo-server'?'/bin/setpriv':'/usr/bin/setpriv','--no-new-privs','--'],targetEntryPoint:hardened.entryPoint,targetCommand:hardened.command??[],workingDirectory:{present:true,value:'/app'},pathEvidence:json({image:images[component],path:x.imageConfigurations[component].Env[0].slice(5),resolvedNode:'/usr/local/bin/node'}),primitiveEvidence:json(x.primitives[component]),healthLaunch:{kind:'absent'}});
  }
  before[key]=old;target[key]=next;addChanges(key,old,next);
  tasks.push({taskKey:key,disposition:'update',containerNames:next.containerDefinitions.map(c=>c.name),phase:key==='backend'?'deploy':'continuation',invocation:key==='backend'?'service':key==='planner'?'worker-planner':'worker-executor',beforeDefinition:json(old,'task-definition'),targetRegistration:json(next,'task-definition'),imageBindings:json(Object.fromEntries(next.containerDefinitions.map(c=>[c.name,images[key==='backend'?c.name:'llm-proxy']]))),baselineEvidence:leaf(key+'-baseline')});
 }
 const purposes={bootstrap:['Mem9Bootstrap','bootstrap-runtime-verify','runtime-verify'],control:['ControlMem9Bootstrap','consolidation-control','control'],promotion:['PromoteMem9Bootstrap','consolidation-promote','promote'],provision:['ProdMem9Bootstrap','denied-provision','deny'],transition:['TransitionMem9Bootstrap','denied-transition','deny']};
 for(const [key,[name,purpose,invocation]]of Object.entries(purposes)){
  const old={family:x.cluster.split('/').at(-1)+'-'+name,networkMode:'awsvpc',requiresCompatibilities:['FARGATE'],runtimePlatform:{cpuArchitecture:'ARM64',operatingSystemFamily:'LINUX'},taskRoleArn:`arn:aws:iam::${x.account}:role/example-${key}`,executionRoleArn:`arn:aws:iam::${x.account}:role/example-execution`,cpu:'256',memory:'512',containerDefinitions:[{name,image:`${x.account}.dkr.ecr.${x.region}.amazonaws.com/mem9-on-aws/bootstrap@sha256:${h('old-control')}`,entryPoint:['node','/bootstrap/original.mjs'],command:[],environment:[],secrets:[],linuxParameters:{initProcessEnabled:true}}]};
  const next={...structuredClone(old),containerDefinitions:[{...controlLaunchPolicy(purpose,old.containerDefinitions[0]),image:slot}]};before[key]=old;target[key]=next;
  const launch={version:1,kind:'guard-first-control-launch',taskKey:key,containerName:name,purpose,entryPoint:next.containerDefinitions[0].entryPoint,command:[],dispatcherPath:'/bootstrap/nonroot-dispatch.mjs',dispatcherSha256:guardSource.files[0].sha256,guardClosure:json(guardSource),originalModule:{present:true,value:'/bootstrap/original.mjs'},originalModuleSha256:{present:true,value:h('old-program')},originalArgv:['/usr/local/bin/node','/bootstrap/original.mjs'],permittedOperations:invocation==='deny'?[]:[invocation],primitiveContract:leaf(key+'-primitive'),buildContractKey:'deployed-bootstrap'};
  controlLaunches.push(launch);
  // The image slot is represented by its exact closed object until postbuild.
  addChanges(key,old,next);
  tasks.push({taskKey:key,disposition:'update',containerNames:[name],phase:['provision','transition'].includes(key)?'registration-only':key==='promotion'?'continuation':'deploy',invocation,beforeDefinition:json(old,'task-definition'),targetRegistration:json(next,'task-definition'),imageBindings:leaf(key+'-image-slot'),baselineEvidence:leaf(key+'-baseline')});
 }
 const fallback={...structuredClone(before.backend),family:x.cluster.split('/').at(-1)+'-Fallback',taskDefinitionArn:`arn:aws:ecs:${x.region}:${x.account}:task-definition/${x.cluster.split('/').at(-1)}-Fallback:1`,revision:1,status:'ACTIVE'};
 tasks.push({taskKey:'fallback',disposition:'retain',containerNames:COMPONENTS,phase:'retained',invocation:'deny',beforeDefinition:json(fallback,'task-definition'),unchangedBindingHash:hash(fallback)});
 tasks.push({taskKey:'preaudit',disposition:'carrier',containerNames:['ControlMem9Bootstrap'],phase:'preaudit',invocation:'readonly-root',beforeDefinition:x.plan.existingControlBinding,targetRegistration:x.plan.registrationBody,carrierBuildHash:hash(carrierBuild),baselineEvidence:leaf('carrier-baseline')});
 before.fallback=fallback;target.fallback=fallback;before.preaudit=a.value(x.plan.registrationBody);target.preaudit=before.preaudit;
 const service={deploymentController:{type:'ECS'},desiredCount:1,deploymentConfiguration:{minimumHealthyPercent:100,maximumPercent:200,deploymentCircuitBreaker:{enable:true,rollback:true}}};
 before.service=service;target.service={...structuredClone(service),deploymentConfiguration:{...service.deploymentConfiguration,deploymentCircuitBreaker:{enable:true,rollback:false}}};
 fieldChanges.push({taskKey:'backend',surface:'service',selector:'Mem9Server',field:'deploymentCircuitBreaker.rollback',before:{present:true,value:true},after:{present:true,value:false},cause:'disable-root-rollback',observationHash:previewEvidence.canonicalHash});
 const invocation={context:'.',file:'docker/bootstrap/Dockerfile',platforms:['linux/arm64'],pull:true,noCacheFilters:['runtime'],buildArgs:[],buildContexts:[],secretMounts:[],ssh:[],target:null,cacheFrom:[],cacheTo:[],buildActionSha:g('control-build-action'),tagRule:'mem9-actual-main-sha7',provenanceRule:'authenticated-workflow-run-attempt'};
 const workflow=sourceFile('.github/workflows/infra-ci.yml',yaml({jobs:{'build-image-transition-control':{steps:[{id:'bootstrap',uses:'docker/build-push-action@'+invocation.buildActionSha,with:{context:'.',file:invocation.file,pull:true,'no-cache-filters':'runtime',platforms:'linux/arm64',push:true}}]}}}));
 const dockerfile=sourceFile('docker/bootstrap/Dockerfile','FROM node:24 AS runtime\nCOPY docker/bootstrap/nonroot-dispatch.mjs /bootstrap/nonroot-dispatch.mjs\n');
 const controlBuildContract={version:1,kind:'reviewed-deployed-control-build-contract',key:'deployed-bootstrap',repository:carrierBuild.source.repository,candidate:deploymentControl,prNumber:carrierBuild.source.prNumber,workflow:{path:workflow.path,sourceFile:workflow,jobKey:'build-image-transition-control',buildStepId:'bootstrap',jobSource:workflow.blob},recipe:{dockerfilePath:dockerfile.path,dockerfile,context:closure(deploymentControl.tree,[dockerfile,...guardSource.files]),ignoreFiles:json([{path:'.dockerignore',present:false},{path:'docker/bootstrap/Dockerfile.dockerignore',present:false}]),preparation:closure(deploymentControl.tree,[]),invocation},guardSource,guardImportPolicy:{version:1,kind:'guard-source-import-policy',allowedBuiltins:NONROOT_GUARD_BUILTINS,guardSource,sourceImportAudit:leaf('guard-source-audit')},launchTemplates:controlLaunches,output:{account:x.account,region:x.region,repositoryName:'mem9-on-aws/bootstrap'},artifactPolicyHash:hash(f.input.policy),guardTestContract:leaf('control-guard-tests'),sourceReview:leaf('control-source-review')};
 const baseline={observedMs:now-1000,service:json(service),task:json(f.legacy.current.backendTask),taskArn:f.legacy.current.backendTask.taskArn,taskDefinitionArn:f.legacy.current.backendTask.taskDefinitionArn,containerBindings:json(f.legacy.current.backendBinding.containers),privateApiEvidence:leaf('old-private-api')};
 const cases=['successful-handover','prefix-start-failure','sidecar-readiness-failure','post-liveness-regression','nonterminal-timeout'].map(name=>({name,startedMs:now-9000,completedMs:now-8000,maximumObservedOutageMs:0,oldTaskPreserved:name!=='successful-handover',deploymentState:name==='successful-handover'?'COMPLETED':name==='nonterminal-timeout'?'IN_PROGRESS':'FAILED',privateApiPassed:true,rootRelaunchCount:0,evidence:leaf(name)}));
 const overlap={version:1,kind:'rolling-healthy-overlap',serviceName:'Mem9Server',strategy:'ROLLING',controller:'ECS',desiredCount:1,minimumHealthyPercent:100,maximumPercent:200,bakeTimeInMinutes:0,circuitBreaker:{enable:true,beforeRollback:true,afterRollback:false},baseline,cloudMap:leaf('cloud-map'),ordinaryWorkflow:json(workflow),rehearsal:{version:1,kind:'bounded-overlap-rehearsal',sourceTree:deploymentControl.tree,dataImages:images,controlBuild:json(carrierBuild),configurationHash:hash(target.service),cases,outcome:'overlap-sufficient',evidence:leaf('availability-evidence'),completedMs:now-8000},maxPlannedOutageMs:7200000};
 const taskPlan={version:2,kind:'exact-nnp-task-plan',policy:NONROOT_HARDENING_POLICY,tasks,fieldChanges,dataLaunches,controlLaunches,previewLaunches:{version:1,kind:'preview-guard-launch-inventory',sourceTree:deploymentControl.tree,entries:leaf('preview-launches'),tests:leaf('preview-tests')},carrierBuild,permissions:x.permissions,overlap,beforeProjection:json(before,'task-definition'),targetProjection:json(target,'task-definition'),deployedControlBuildContract:controlBuildContract,previewEvidence};
 inspectNonrootRecord('TaskPlanV2',taskPlan);json(taskPlan,'protocol','task-plan.json');
 const input={version:2,kind:'ecs-nonroot-image-upgrade-proof',limits:NONROOT_LIMITS,predecessorParameter:x.predecessorParameter,legacyBootstrapProof:x.legacyBootstrapProof,root,dataOrigin:x.dataOrigin,historicalCopy:x.historicalCopy,artifactReverification:x.artifactReverification,deploymentControl,protectedInputs:x.protectedInputs,taskPlan,predeploymentAudit:x.predeploymentAudit,artifactSecurity:x.artifactSecurity,policySources:x.policySources,designReview:x.designReview,observedMs:now};
 inspectNonrootRecord('NonrootImageProofV2',input);
 return {...x,input,taskPlan,before,target,fallback,controlBuildContract,evidence:{archive:a.archive(),graphVerification:f.graphVerification,filesystemVerification:x.filesystems}};
}

/** Synthetic final-review/descriptor values; callers must still build and bind
 * the real proof context. This does not create an authorization brand. */
export function nonrootAuthorizationValues(f,built,bindings){
 const p=built.proof;
 const review={version:2,kind:'nonroot-deployment-policy-review',decision:'pass-for-deployment',proofHash:built.proofHash,designReviewHash:p.designReview.canonicalHash,sourceEvidenceHash:p.deploymentControl.sourceEvidence.canonicalHash,dataOriginSourceEvidenceHash:p.dataOrigin.sourceEvidence.canonicalHash,copyAdoptionHash:hash(p.historicalCopy),artifactReverificationHash:hash(p.artifactReverification),taskPlanHash:hash(p.taskPlan),carrierBuildHash:hash(p.taskPlan.carrierBuild),permissionsHash:hash(p.taskPlan.permissions),availabilityRehearsalHash:hash(p.taskPlan.overlap.rehearsal),policySourcesHash:p.policySources.canonicalHash,artifactSecurityHash:p.artifactSecurity.canonicalHash,oldRootAuditHash:hash(p.predeploymentAudit),predecessorHash:bindings.predecessorHash,controlSourceTree:p.deploymentControl.tree,reviewedMs:f.now,expiresMs:f.now+3600000};
 const current={...structuredClone(f.f.predecessor),version:3,controlSourceTree:p.deploymentControl.tree,dataRevision:p.dataOrigin.revision,dataSourceTree:p.dataOrigin.tree,dataSourceTag:'mem9-'+p.dataOrigin.revision.slice(0,7),images:structuredClone(bindings.images),authorizationId:f.owner,issuedMs:review.reviewedMs,expiresMs:review.expiresMs,policyHash:hash(review),buildInputsHash:bindings.buildInputsHash,securityEvidenceHash:bindings.securityEvidenceHash,transition:{version:2,kind:'image-security-nonroot-upgrade',proofHash:built.proofHash,predecessorHash:bindings.predecessorHash,limitsHash:bindings.limitsHash}};
 return {review,current};
}
