import {createHash} from 'node:crypto';
import {canaryEvidenceHash as hash} from './lib/production-canary-verification.mjs';
import {normalizeCanaryTask} from './lib/production-canary-material.mjs';
import {normalizeCanaryAuthority} from './lib/production-canary-producer.mjs';
import {expectedBoundaryPolicyDocument} from './lib/workload-permissions-boundary.mjs';
export const OLD_SCOPE_ACTIONS=['bedrock-mantle:CreateInference','bedrock-mantle:GetProject','bedrock-mantle:ListProjects','bedrock-mantle:ListTagsForResource','ecr:BatchCheckLayerAvailability','ecr:BatchGetImage','ecr:GetDownloadUrlForLayer','lambda:InvokeFunction','logs:CreateLogGroup','logs:CreateLogStream','logs:PutLogEvents','s3:GetObject','s3:PutObject','secretsmanager:GetSecretValue','sns:Publish','sqs:SendMessage','ssm:GetParameters','ssm:PutParameter'];
export const semantic=v=>Array.isArray(v)?v.map(semantic).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b))):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).filter(k=>k!=='Sid').sort().map(k=>[k,semantic(v[k])])):v;
export const sha=v=>createHash('sha256').update(v).digest('hex');
const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;
export function transitionFixture(){
 const account='123456789012',region='ap-northeast-1',h=c=>c.repeat(64),digest=c=>'sha256:'+h(c),at=1800000000000,cluster='mem9-on-aws-prod-Fixture',clusterArn=`arn:aws:ecs:${region}:${account}:cluster/${cluster}`;
 const parameters={ApplicationRegion:region,DecisionArtifactBucketName:'mem9-audit-'+account,BedrockProjectArn:`arn:aws:bedrock-mantle:${region}:${account}:project/proj_fixture`,OpenAiBedrockProjectArn:''};
 const after=semantic(expectedBoundaryPolicyDocument({partition:'aws',accountId:account,applicationRegion:region,decisionArtifactBucketName:parameters.DecisionArtifactBucketName,bedrockProjectArn:parameters.BedrockProjectArn}));
 const before=structuredClone(after);before.Statement=before.Statement.filter(s=>!s.Action?.includes?.('iam:PassRole'));before.Statement.find(s=>Array.isArray(s.NotResource)).Action=OLD_SCOPE_ACTIONS.slice().sort();before.Statement=semantic(before.Statement);
 const snapshots=[false,true].map(next=>{
  const ref=name=>`${account}.dkr.ecr.${region}.amazonaws.com/mem9-on-aws/${name}@${digest('a')}`,component=name=>({registryId:account,repositoryName:'mem9-on-aws/'+name,rootDigest:digest('a'),arm64Digest:digest('b')});
  const make=(kind,names)=>({taskDefinitionArn:`arn:aws:ecs:${region}:${account}:task-definition/${cluster}-${kind}:${next?2:1}`,family:cluster+'-'+kind,revision:next?2:1,status:'ACTIVE',registeredAt:'2026-01-01T00:00:00.000Z',networkMode:'awsvpc',cpu:'512',memory:'1024',runtimePlatform:{cpuArchitecture:'ARM64',operatingSystemFamily:'LINUX'},requiresCompatibilities:['FARGATE'],taskRoleArn:`arn:aws:iam::${account}:role/mem9-on-aws-prod-${kind}-task`,executionRoleArn:`arn:aws:iam::${account}:role/mem9-on-aws-prod-${kind}-exec`,containerDefinitions:names.map(name=>({name,image:ref(name==='planner'||name==='executor'?'llm-proxy':name),environment:[],secrets:[]}))});
  const definitions={planner:make('Planner',['planner']),executor:make('Executor',['executor']),backend:make('Mem9RuntimeServer',['llm-proxy','mnemo-server','qwen3-embed'])};
  Object.assign(definitions.backend,{compatibilities:next?['MANAGED_INSTANCES','FARGATE','EC2']:['EC2','FARGATE','MANAGED_INSTANCES'],requiresAttributes:[{name:'ecs.capability.task-eni'},...(next?[{name:'com.amazonaws.ecs.capability.docker-remote-api.1.21'}]:[])]});
  const backendBinding={taskArn:`arn:aws:ecs:${region}:${account}:task/${cluster}/`+(next?'b':'a').repeat(32),taskDefinitionArn:definitions.backend.taskDefinitionArn,containers:['llm-proxy','mnemo-server','qwen3-embed'].map(name=>({name,imageDigest:digest('b')}))};
  const scheduler={roleArn:`arn:aws:iam::${account}:role/mem9-on-aws-prod-Mem9ConsolidationSchedulerRole-role`,groupName:'mem9-on-aws-prod-consolidation-fixture'};
  const authority=[...Object.values(definitions).flatMap(d=>[d.taskRoleArn,d.executionRoleArn]),scheduler.roleArn].sort().map((arn,i)=>({arn,roleId:'FixtureRole'+i,path:'/',maxSessionDuration:3600,trust:{Version:'2012-10-17',Statement:[]},tags:[],inlinePolicies:[],attachedPolicies:[],boundary:{arn:`arn:aws:iam::${account}:policy/mem9-on-aws-workload-boundary`,document:structuredClone(next?after:before)}}));
  const role=authority.find(r=>r.arn===scheduler.roleArn);role.trust={Version:'2012-10-17',Statement:[{Effect:'Allow',Action:'sts:AssumeRole',Principal:{Service:'scheduler.amazonaws.com'},Condition:{StringEquals:{'aws:SourceAccount':account,'aws:SourceArn':`arn:aws:scheduler:${region}:${account}:schedule-group/${scheduler.groupName}`}}}]};
  role.inlinePolicies=[{name:'inline',document:{Version:'2012-10-17',Statement:[{Effect:'Deny',Action:'ecs:RunTask',Resource:`arn:aws:ecs:${region}:${account}:task-definition/${cluster}-Mem9Consolidation:*`},{Effect:'Allow',Action:'ecs:RunTask',Resource:[definitions.planner.taskDefinitionArn,definitions.executor.taskDefinitionArn],Condition:{ArnEquals:{'ecs:cluster':clusterArn}}},{Effect:'Allow',Action:'iam:PassRole',Resource:[definitions.planner.taskRoleArn,definitions.planner.executionRoleArn,definitions.executor.taskRoleArn,definitions.executor.executionRoleArn],Condition:{StringEquals:{'iam:PassedToService':'ecs-tasks.amazonaws.com'}}}]}}];
  return {version:2,observedAt:new Date(at).toISOString(),account,region,revision:(next?'b':'a').repeat(40),sourceTree:(next?'b':'a').repeat(40),coordinatorDigest:h(next?'c':'d'),generation:h('e'),sourceTag:'mem9-aaaaaaa',workerImage:ref('llm-proxy'),runtime:{schemaDigest:h('1'),operatorDigest:h('2'),runtimeNonce:'c'.repeat(32)},components:{worker:component('llm-proxy'),...Object.fromEntries(['llm-proxy','mnemo-server','qwen3-embed'].map(n=>[n,component(n)]))},definitions,backendBinding,backendTask:{taskArn:backendBinding.taskArn,taskDefinitionArn:backendBinding.taskDefinitionArn,clusterArn,lastStatus:'RUNNING',healthStatus:'HEALTHY',launchType:'FARGATE',cpu:'512',memory:'1024',startedAt:'2026-01-01T00:00:00.000Z',attributes:[{name:'ecs.cpu-architecture',value:'arm64'}],containers:definitions.backend.containerDefinitions.map(c=>({...c,imageDigest:digest('b'),healthStatus:'HEALTHY'}))},authority,scheduler,credentials:[],network:{cluster:clusterArn,subnets:['subnet-abcd'],securityGroups:['sg-abcd'],assignPublicIp:'DISABLED'},material:{}};
 });
 const [previous,current]=snapshots,release=s=>({sourceTree:s.sourceTree,coordinatorDigest:s.coordinatorDigest,sourceTag:s.sourceTag,workerImage:s.workerImage,...s.runtime});
 const parent={generation:previous.generation,validationId:'d'.repeat(32),targets:['11111111-1111-4111-8111-111111111111'],workerImage:previous.workerImage,sourceTag:previous.sourceTag,backendBindingHash:hash(previous.backendBinding),releaseHash:hash(release(previous)),changedRows:10,receipts:5,conservationHash:h('3')};
 const data={version:1,stage:'prod',account,region,controlSourceTree:current.sourceTree,dataRevision:previous.revision,dataSourceTree:previous.sourceTree,dataSourceTag:previous.sourceTag,images:Object.fromEntries(['llm-proxy','mnemo-server','qwen3-embed'].map(n=>[n,{rootDigest:digest('a'),arm64Digest:digest('b')}])),parentProofHash:hash(parent),backendBindingHash:parent.backendBindingHash,runtimeNonce:previous.runtime.runtimeNonce,generation:previous.generation,targetsHash:hash(parent.targets),schemaDigest:previous.runtime.schemaDigest,operatorDigest:previous.runtime.operatorDigest,buildInputsHash:h('4'),securityEvidenceHash:h('5'),policyHash:h('6'),authorizationId:'e'.repeat(32),issuedMs:at-1000,expiresMs:at+3600000};
 current.dataRelease={data,hash:hash(data),parameterVersion:2};current.controlSourceTag='mem9-bbbbbbb';
 const refresh=s=>{const images=new Map([[s.workerImage,s.components.worker]]);for(const c of s.definitions.backend.containerDefinitions)images.set(c.image,s.components[c.name]);for(const kind of ['planner','executor','backend'])s.material[kind]=hash(normalizeCanaryTask(s.definitions[kind],{account,region,images}));for(const kind of ['network','credentials'])s.material[kind]=hash(s[kind]);s.material.authority=hash(normalizeCanaryAuthority(s));};snapshots.forEach(refresh);
 const boundaryTemplate='synthetic reviewed boundary template\n',operation={version:1,attempt:'f'.repeat(32),bindingHash:h('7'),source:{commit:'c'.repeat(40),tree:'d'.repeat(40)},bindings:{accountId:account,applicationRegion:region,stacks:{boundary:{arn:`arn:aws:cloudformation:us-west-2:${account}:stack/example/fixture`,parameters}}},templateHashes:{boundary:{source:sha(boundaryTemplate),wire:sha(boundaryTemplate)}}};
 let prior=h('0');const controlChain=['READ_ONLY','ARMED','SUCCEEDED'].map((phase,i)=>{const record={version:1,attempt:operation.attempt,bindingHash:operation.bindingHash,sequence:i+1,event:i===2?'succeeded':'fixture',phase},entry={version:1,previousHash:prior,record,hash:sha(prior+'\n'+JSON.stringify(canonical(record)))};prior=entry.hash;return entry;});
 const bootstrap={operation,controlChain,boundaryTemplate},expectedBootstrap={attempt:operation.attempt,operationHash:hash(operation),terminalHash:prior,sourceCommit:operation.source.commit,sourceTree:operation.source.tree,boundaryTemplateHash:sha(boundaryTemplate),parametersHash:hash(parameters),previousPolicyHash:hash(before),currentPolicyHash:hash(after)};
 return {previous,current,parent,bootstrap,expectedBootstrap,now:at,refresh,input:()=>({previousText:JSON.stringify(previous),currentText:JSON.stringify(current),parent,bootstrap}),selection:()=>({revision:current.revision,sourceTree:current.sourceTree,coordinatorDigest:current.coordinatorDigest,dataReleaseHash:current.dataRelease.hash,parameterVersion:current.dataRelease.parameterVersion})};
}
